name: Docs

on:
  push:
    branches:
      - master
  # pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate dokka files
        run: ./gradlew :adam:dokkaGeneratePublicationHtml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/api

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
