name: Build and deploy docs

on:
  push:
    branches:
      - master

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
        
      - name: Generate dokka files
        run: ./gradlew :adam:dokkaGenerate
      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          jekyll_src: docs
          target_branch: gh-pages
          gem_src: docs
